spring:
    profiles:
        active: native
    application:
        name: config-server
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/config-repo
                fail-fast: true
                fail-on-empty: true
server:
        port: 8888